-- Drop all tables script

DROP TABLE IF EXISTS WorksIn;
DROP TABLE IF EXISTS Manager;
DROP TABLE IF EXISTS Cleaner;
DROP TABLE IF EXISTS Student;
DROP TABLE IF EXISTS Worker;
DROP TABLE IF EXISTS Room;
DROP TABLE IF EXISTS Building;
DROP TABLE IF EXISTS Person;
